# Generated by Django 4.2 on 2023-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tag_alter_news_date_remove_news_tags_news_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='news',
            name='news_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.ManyToManyField(to='api.keywords'),
        ),
    ]
