# Generated by Django 4.2 on 2023-05-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_keywords_remove_news_keywords_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='news_name',
            new_name='name',
        ),
    ]
